### ISSUE TITLE
Add building height as an attribute after map creation

### ISSUE THREAD

**Issue by sleeping-hedgehog** [cse-bristol/110-thermos-ui#17]
When creating a map with LiDAR data, it would be good if the map created had building height as an attribute. I'm hoping this wouldn't be too tricky since building heights must be calculated at some point during map creation to go into the 3d demand model.

Why?
1. It would be useful to check whether the LiDAR data has given sensible outputs in places where we use unfamiliar LiDAR data (e.g. Europe rather than GB)
2. It would be useful to show to clients who are surprised about a particularly high or low demand.
3.  It would be useful to have this attribute attached to the data if downloaded as a GIS file as well. Could be used for other bits of analysis.
4. It would just be interesting.

**Comment by larkery** [comment]
This should appear in the network editor and I think in the downloads as well.

**Comment by larkery** [comment]
Will shortly be deployed into live; unfortunately won't apply retroactively to existing problems. I could make that happen though actually.
