### ISSUE TITLE
"Hide/show unconstrained candidates" button wiping user edits

### ISSUE THREAD

**Issue by sleeping-hedgehog** [cse-bristol/110-thermos-ui#8]
**Describe the bug**
Pressing the "hide unconstrained candidates" button seems to wipe user edits. I noticed this when I added a new field and the new field disappeared when I pressed the button. 

**To Reproduce**
1. Select some buildings
2. Press e
3. Go to other fields and create your own field (e.g. Region)
4. Click "hide unconstrained candidates"
5. Field will be gone

**Expected behavior**
User created fields, and more generally user edits, should live on even after the "hide unconstrained candidates" button is clicked

**Comment by larkery** [comment]
This is now fixed, I believe
